### ISSUE TITLE
Fuzzy matching

### ISSUE THREAD

**Issue by jasonm23** [story-branch/story_branch#12]
To define more clearly;

My interpretation of fuzzy matching would find matches for words in the search string in any order on the story names. eg.

```
search text: table change report[TAB]

match names containing: change report table, table report change, report change table etc. 
(as a substring contained in the full story name)
```

As a second level of fuzziness, find "similar" strings using Levenshtein distance, eg:

```
search text: tble[TAB]

match a name containing: table (or similar)
```

This second level of fuzziness may be moved out to another issue, and implemented later.

As a third level, ignore any punctuation in the match strings (and search string?) I haven't thought about this much but as an eg:

```
search text:  this blue egg

would match a name containing:  this/blue::egg
```

**Comment by rpbaltazar** [comment]
This is trickier to achieve and depends on TTY so closing the issue for now
