### ISSUE TITLE
Allow the user to define the preferred word for git finish

### ISSUE THREAD

**Issue by rpbaltazar** [story-branch/story_branch#27]
Currently `git finish` uses `Finishes` as the default word. It's not always the case in everyones workflow.
I'd propose that setting the preferred expression is allowed in `.story_branch` file.
e.g

```
api: 123892138021
project: 123312
finish_tag: Resolves
```

**Comment by jasonm23** [comment]
Sounds good.  I'm no longer maintaining this actively, I can add you as a contributor Rui @rpbaltazar 

Maybe even move this to an org called storybranch

**Comment by rpbaltazar** [comment]
Sounds good.
I don't mind taking over the maintenance of the gem either.
We still use on a daily basis.

I've created the organization and invited you to it.

**Comment by jasonm23** [comment]
Hi Rui, can you set me as a contributor instead of a member, so I can setup CircleCI please?

**Comment by jasonm23** [comment]
#31

**Comment by rpbaltazar** [comment]
Changed you to admin. Sorry for the delay, but only had time to go over the notifications now.

**Comment by jasonm23** [comment]
Closed by #27
