### ISSUE TITLE
Support multiple project configurations

### ISSUE THREAD

**Issue by rpbaltazar** [story-branch/story_branch#32]
I'm currently working with two different accounts in Pivotal Tracker therefore there is no nice way of dealing with this since the api key will be different and i don't want to submit my api key to the project repo.

This would also open the possibility of supporting other trackers.

**Comment by jasonm23** [comment]
Hi @rpbaltazar is this to support multiple tracker accounts in the same repo?

Maybe describe the feature using BDD/Gherkin GIVEN, WHEN, THEN style. (It enforces finite states instead of an open ended interpretation)

**Comment by rpbaltazar** [comment]
Sounds good @jasonm23 
I wrote it down mainly not to forget what I was thinking. I'm working on it for the kicks and I'll describe it better later on.

But generally that is the idea. Make it simpler to have projects that should use a different API key.

The simplest use case at the moment is if one works in two different projects and there are two different tracker accounts. Although possible to do it by changing the environment variable, so one can write a simple switcher, it is not necessarily the nicest.

Also, having the flexibility of multiple projects configurations, opens the doors to support different trackers, which I'll be happy to work on later as well.

**Comment by jasonm23** [comment]
Proposed .yml, let's see if I understand the idea correctly.

We can continue to support:

```
api: $API_TOKEN
project: $PROJECT_ID
```

in addition we could support:

```
sources:
  - type: pivotaltracker
    name: Project A
    api: $API_TOKEN_1
    project: $PROJECT_ID_2
  - type: pivotaltracker
    name: Project B
    api: $API_TOKEN_1
    project: $PROJECT_ID_2
```

When we get our stories we'd see:

```
Project A: (pivotal tracker)
32984732 - My story from my project
16654732 - Some other thing with a terrible title
32094821 - Do the entire backend 
Project B: (pivotal tracker)
132298746 - My front end story
324198732 - Fix that bug
2984371113 - Some Chore
```

**Comment by jasonm23** [comment]
@rpbaltazar - I guess there is something about this story which makes me worried about the use case.  

The blunt question is:

> Why are we using multiple activity tracking systems on one repo?

**Comment by rpbaltazar** [comment]
The whole idea on how to get it to work is clearly understood, but the blunt question does not cover the use case. Currently the assumption is that with one api key we have access to all projects. And then having a .story_branch file in the root of the project we can get the stories associated with that project.

Happens that you can have projects that are tracked in Pivotal Tracker, or projects that are tracked only on GitHub or even (specially on a consulting basis) projects that are tracked under different Pivotal Tracker accounts (e.g rui@opsmanager.com and rui@pivotallabs.com). 

With the current implementation of story branch there are two possible solutions to cover this use case:

1. Have the story_branch file in the project folder with both api key and project id
  - Not really ideal because then you should not commit the .story_branch file to the repo. This would then force new collaborators to setup their own file.
2. Have the possible api keys in different environment variables and have a quick switch trigger that would reset the env variable depending on which project you're working on
  - Cleaner (in my opinion) but also not ideal

So currently it is possible to solve this use case but none of the solutions is really neat. Plus if we want to integrate with other trackers then it is definitely not possible.

As I've mentioned earlier, this past few days I've started playing with a set of gems and i've started re-writting story_branch to have this capability. Take a look at the [using-tty](https://github.com/story-branch/story_branch/tree/using-tty) branch.

I'm very keen in using more of these small utils, namely [pager](https://github.com/piotrmurach/tty-pager) and [prompt](https://github.com/piotrmurach/tty-prompt)
