### ISSUE TITLE
Assign me to owners of the gem in rubygems

### ISSUE THREAD

**Issue by rpbaltazar** [story-branch/story_branch#39]
Currently @jasonm23, you are the sole owner of Story Branch in ruby gems.

Can you please add me to the list of owners?

I've been working on this and there are a couple more features I'd like to release in the near future.

**Comment by jasonm23** [comment]
I'll have a look at rubygems and see what needs doing.

We should just set it up so that a tag bump + successful test run does a CI/CD release and pushes a new gem.

**Comment by jasonm23** [comment]
@rpbaltazar  let me know what your rubygems account id/email is, it will be linked up as an owner.

**Comment by jasonm23** [comment]
(assuming and adding your Gmail.)

**Comment by rpbaltazar** [comment]
Perfect! Thanks
