### ISSUE TITLE
Keep track of a Change log

### ISSUE THREAD

**Issue by rpbaltazar** [story-branch/story_branch#41]
It would be useful to have a change log up to date. 

If possible, update based on the past versions as well

**Comment by jasonm23** [comment]
Added WIP Changelog - fce2b94e96959ae592473af9d5fcaa19067ba35b

Removed all crufty commits.  Left commit info for review.  

@rpbaltazar you can decide on the Changelog format.

I'd suggest the following let me know, and I'll parse the current Changelog WIP into that format if you like.

- - -

## v0.0.0

- Foobar checking added
- etc.

## v0.0.0

- Barbaz issue was resolved #41
- etc.
- etc.

## v0.0.0

- etc.

**Comment by rpbaltazar** [comment]
Change log format looks good to me. I'd probably add the release date in front of the version.

**Comment by jasonm23** [comment]
How about:

## v0.1.3 - 2018-06-29

- Foobar checking added
- etc.

## v0.1.2 - 2018-05-01

- Barbaz issue was resolved #41
- etc.
- etc.

## v0.1.1 - 2018-02-17

- etc.

**Comment by jasonm23** [comment]
Or:


How about:

## v0.1.3
2018-06-29

- Foobar checking added
- etc.

## v0.1.2
2018-05-01

- Barbaz issue was resolved #41
- etc.
- etc.

## v0.1.1
2018-02-17

- etc.

**Comment by rpbaltazar** [comment]
Yes. Agreed. Last version ok.

**Comment by jasonm23** [comment]
:+1:

**Comment by jasonm23** [comment]
Done for the project history - ./Changelog.md
