### ISSUE TITLE
Alter release tag format to be consistent with gem VERSION value

### ISSUE THREAD

**Issue by jasonm23** [story-branch/story_branch#47]
To simplify automation of the release process we could change the tag format to:

    ^[0-9]+\.[0-9]+\.[0-9]+$

instead of the current style.

    ^v[0-9]+\.[0-9]+\.[0-9]+$

@rpbaltazar - add your approval and let's ensure the format is used going forward.

We can later add a chore where Circle does it's own tagging based on discovery of a new `VERSION`

**Comment by rpbaltazar** [comment]
Fine for me.

**Comment by jasonm23** [comment]
Thanks
