### ISSUE TITLE
Follow XDG for file storage

### ISSUE THREAD

**Issue by peterhoeg** [story-branch/story_branch#90]
## Describe the steps to reproduce

sb currently dumps the credentials in $HOME/.story_branch.yml - it would be very nice to to follow XDG instead to avoid polluting $HOME: https://github.com/bkuhlmann/xdg

### What did you expect to happen?

.story_branch.yml to end up in $XDG_DATA_HOME/story_branch.

### Additional information

The xdg path will also work on mac.

**Comment by rpbaltazar** [comment]
For this to be implemented without breaking changes I'll probably extract the configuration management logic to its own and link it closer to the project.

Ideally, the changes path should be:
1. Default the creation of the files following XDG.
2. When reading the configurations, if there is a file in the 'old path' then read that one
3. If there is no file in the 'old path', read from xdg

**Comment by rpbaltazar** [comment]
I think this is more suitable for the 0.7.0 release actually.
