### ISSUE TITLE
If using JIRA and no status To Do then no issues are returned

### ISSUE THREAD

**Issue by brilyuhns** [story-branch/story_branch#94]
Before submitting an issue, please be sure to update to the latest Gem version

### Describe the steps to reproduce

project configured as JIRA.

`story_branch create`

returns no tickets assigned to me

### What happened instead?

Paste in any error messages using [code-fences](https://help.github.com/articles/creating-and-highlighting-code-blocks/)

**Comment by rpbaltazar** [comment]
Ideally we would support the jql query to be defined as a setting rather than hard coded.
