### ISSUE TITLE
Support creating tickets from keywords other than TODO

### ISSUE THREAD

**Issue by peterhoeg** [story-branch/story_branch#97]
## What did you expect to happen?

Would be great if it was possible to either autodetect additional keywords (such as `xcontext` or `xit` when using rspec) or have the user configure a set of keywords to also look for in addition to `TODO` when automatically creating tickets

### What happened instead?

Currently unsupported.

**Comment by rpbaltazar** [comment]
This belongs to the todo_agent tool instead of story branch https://github.com/story-branch/todo_agent/issues/14
